"use strict"

// require("babel/register")({
//   only: /src\/client\/src/,
//   ignore: false
// })


const game = require("./")
const root = "http://localhost:3000"

game.autoLook()
game.autoControls()
game.to(root, "text/plain")
  .then(() => game.body())
  .then(() => game.to(root, "application/json"))
  .then(() => game.body())
  .then(() => game.json())
  .then(() => game.to(root, "application/vnd.siren+json"))
  .then(() => game.yaml())
  .then(() => game.to(root, "application/x.star+json"))
  .then(() => game.yaml())
  .then(() => game.do("start", {name: "HX"}))
  .then(() => game.follow())
  .then(() => game.look())
  .then(() => game.links())
  .then(() => game.go(0))
  .then(() => game.look())
  .then(() => game.links())
  .then(() => game.go(1))
  .then(() => game.look())
  .then(() => game.links())
  .then(() => game.actions())
  .then(() => game.do("open_door"))
  .then(() => game.look())
  .then(() => game.links())
  .then(() => game.go(1))
  .then(() => game.yaml())
  .then(() => game.get("application/x.star+json;version=2"))
  .then(() => game.yaml())
  .then(() => game.do("write", {text: "LOL!"}))
  .then(() => game.look())
  .then(() => game.do("open_door"))
  .then(() => game.look())
  .then(() => game.auth("", "2342"))
  .then(() => game.look())
  .then(() => game.follow())
  .then(() => game.look())
  .then(() => game.links())
  .then(() => game.go(0))
  .then(() => game.look())
  .then(() => game.actions())
  .then(() => game.do("hit_enter"))
  .then(() => game.look())
  .then(() => game.actions())
  .then(() => game.do("type_halt"))
  .then(() => game.look())
  .then(() => game.actions())
  .then(() => game.do("type_hqlt"))
  .then(() => game.look())
  .then(() => game.actions())
  .then(() => game.do("type_fuck"))
  .then(() => game.look())
  .then(() => game.follow())
  .then(() => game.look())
  .then(() => game.wait(3))
  .then(() => game.go(0))
  .then(() => game.look())
  .then(() => game.wait(3))
  .then(() => game.go(0))
  .then(() => game.follow())
  .then(() => game.look())
  .then(() => game.options())
  .then(() => game.delete())
  .then(() => game.get())
  .then(() => game.follow())
  .then(() => game.look())
  .then(() => game.links())
  .then(() => game.go(1))
  .then(() => game.look())
  .then(() => game.links())
  .then(() => game.go(1))
  .then(() => game.go(1))
  .then(() => game.go(0))
  .then(() => game.go(0)) // 307 time travel
  .then(() => game.follow())
  .then(() => game.go(0)) // control room past
  .then(() => game.go(0)) // corridor past
  .then(() => game.go(0)) // hanger past
  .then(() => game.go(0)) // corridor past
  .then(() => game.go(1)) // third door past
  .then(() => game.do("write", {text: "2341"}))
  .then(() => game.do("write", {text: "2342"}))
  .then(() => game.go(0)) // 303
  .then(() => game.follow()) // paradox
